[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v

# 当我运行 pytest 时，只去 tests/ 目录寻找测试。
# 找文件名为 test_*.py 的文件。
# 其中测试类以 Test 开头。
# 测试函数以 test_ 开头。
# 最后使用详细模式输出测试结果